---
- hosts: blog

  tasks:
  - name: ping
    ping:

  - name: install packages
    apt: name={{ item }} update_cache=yes
    with_items:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: true

  - name: add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: add Docker's repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    become: true

  - name: install docker
    apt: name={{ item }} update_cache=yes
    with_items:
      - docker-ce
    become: true
